const RAW='https://raw.githubusercontent.com/ronandownes/restricted-dog-cnn/main';
const colors={Accuracy:'#2c6fb0',Precision:'#d87922',Recall:'#22865a',F1:'#c84444'};
const models=[
{name:'VGG16',year:'2014 · Uniform deep CNN',Accuracy:87.4,Precision:60.3,Recall:92.1,F1:72.9},
{name:'ResNet50',year:'2015 · Residual connections',Accuracy:91.7,Precision:70.9,Recall:93.7,F1:80.7},
{name:'InceptionV3',year:'2015 · Multi-scale processing',Accuracy:96.1,Precision:84.4,Recall:96.8,F1:90.2},
{name:'Xception',year:'2016 · Separable convolutions',Accuracy:96.0,Precision:83.7,Recall:97.4,F1:90.0},
{name:'InceptionResNetV2',year:'2016 · Inception + residual',Accuracy:96.8,Precision:86.9,Recall:97.4,F1:91.8},
{name:'NASNetMobile',year:'2017 · Architecture search',Accuracy:94.8,Precision:79.9,Recall:96.3,F1:87.4}
];
const cases=[
['FN','Staffordshire Bull Terrier','FN_staffordshire_bullterrier_n02093256_2987_gradcam.png'],['FN','Staffordshire Bull Terrier','FN_staffordshire_bullterrier_n02093256_5325_gradcam.png'],['FN','Staffordshire Bull Terrier','FN_staffordshire_bullterrier_n02093256_5988_gradcam.png'],['FP','Black-and-tan Coonhound','FP_black-and-tan_coonhound_n02089078_1454_gradcam.png'],['FP','Kelpie','FP_kelpie_n02105412_7370_gradcam.png'],['FP','Weimaraner','FP_weimaraner_n02092339_3028_gradcam.png'],['TN','Curly-coated Retriever','TN_curly-coated_retriever_n02099429_1465_gradcam.png'],['TN','Greater Swiss Mountain Dog','TN_greater_swiss_mountain_dog_n02107574_2662_gradcam.png'],['TN','Kelpie','TN_kelpie_n02105412_7810_gradcam.png'],['TP','German Shepherd','TP_german_shepherd_n02106662_13368_gradcam.png'],['TP','Rottweiler','TP_rottweiler_n02106550_4962_gradcam.png'],['TP','Staffordshire Bull Terrier','TP_staffordshire_bullterrier_n02093256_8205_gradcam.png']];
let i=0,bChart,fChart;
const valueLabels={id:'values',afterDatasetsDraw(c){const x=c.ctx;x.save();x.font='800 13px system-ui';x.textAlign='center';x.fillStyle='#122033';c.data.datasets.forEach((d,di)=>c.getDatasetMeta(di).data.forEach((bar,j)=>{if(d.data[j]!=null)x.fillText(Number(d.data[j]).toFixed(1)+'%',bar.x,bar.y-7)}));x.restore()}};Chart.register(valueLabels);
function story(n){return [
['Baseline established','VGG16 begins with strong recall, but precision and F1 leave substantial room for improvement.'],
['A clear step forward','ResNet50 improves all four headline metrics, with especially large gains in precision and F1.'],
['The benchmark moves into the mid-90s','InceptionV3 produces another substantial improvement across all four headline metrics.'],
['Newer does not mean uniformly better','Xception raises recall slightly, but accuracy, precision and F1 edge down relative to InceptionV3.'],
['Best frozen balance','InceptionResNetV2 improves accuracy, precision and F1 while recall stays level. It is selected for fine-tuning.'],
['Historical progress is not task-specific progress','NASNetMobile is historically later, yet all four headline metrics decline relative to InceptionResNetV2.']][n]}
function update(){const m=models[i],s=story(i),keys=['Accuracy','Precision','Recall','F1'];count.textContent=`${i+1} of 6`;model.textContent=m.name;year.textContent=m.year;headline.textContent=s[0];commentary.textContent=s[1];prev.disabled=i===0;next.disabled=i===5;tiles.innerHTML=keys.map(k=>`<div class="tile" style="--c:${colors[k]}"><small>${k}</small><b>${m[k].toFixed(1)}%</b></div>`).join('');if(i===0)deltas.innerHTML='<div class="delta"><span>Comparison</span><b>Starting point</b></div>';else{const p=models[i-1];deltas.innerHTML=keys.map(k=>{const d=+(m[k]-p[k]).toFixed(1),cl=Math.abs(d)<.05?'':d>0?'up':'down',ar=Math.abs(d)<.05?'→':d>0?'↑':'↓';return `<div class="delta ${cl}"><span>${k} vs ${p.name}</span><b>${ar} ${d>0?'+':''}${d.toFixed(1)} pts</b></div>`}).join('')}bChart.data.datasets[0].data=keys.map(k=>m[k]);bChart.update()}
window.addEventListener('DOMContentLoaded',()=>{bChart=new Chart(document.getElementById('benchmarkChart'),{type:'bar',data:{labels:['Accuracy','Precision','Recall','F1'],datasets:[{data:[],backgroundColor:[colors.Accuracy,colors.Precision,colors.Recall,colors.F1],borderRadius:10,maxBarThickness:88}]},options:{responsive:true,maintainAspectRatio:false,plugins:{legend:{display:false}},scales:{y:{min:55,max:100,ticks:{callback:v=>v+'%'},title:{display:true,text:'Test performance (%)'}},x:{grid:{display:false}}}}});fChart=new Chart(document.getElementById('fineChart'),{type:'bar',data:{labels:['Accuracy','Precision','Recall','F1'],datasets:[{label:'Frozen',data:[97.08,87.38,98.42,92.57],backgroundColor:'#9aa8ba',borderRadius:8},{label:'Fine-tuned',data:[98.25,93.88,96.84,95.34],backgroundColor:[colors.Accuracy,colors.Precision,colors.Recall,colors.F1],borderRadius:8}]},options:{responsive:true,maintainAspectRatio:false,plugins:{legend:{position:'bottom'}},scales:{y:{min:84,max:100,ticks:{callback:v=>v+'%'},title:{display:true,text:'Performance (%)'}},x:{grid:{display:false}}}}});const fr={Accuracy:97.08,Precision:87.38,Recall:98.42,F1:92.57},ft={Accuracy:98.25,Precision:93.88,Recall:96.84,F1:95.34};fineDeltas.innerHTML=['Accuracy','Precision','Recall','F1'].map(k=>{const d=+(ft[k]-fr[k]).toFixed(2),cl=d>0?'up':'down',ar=d>0?'↑':'↓';return `<div class="delta ${cl}"><span>${k}</span><b>${ar} ${d>0?'+':''}${d.toFixed(2)} pts</b></div>`}).join('');gallery.innerHTML=cases.map(([cat,breed,file])=>{const url=`${RAW}/gradcam/figures/${file}`,lab={TP:'True positive',TN:'True negative',FP:'False positive',FN:'False negative'}[cat];let note='Representative case from the fixed twelve-image explanation sample.';if(file.includes('german_shepherd'))note='Attention concentrated around the head and ears in this correctly restricted prediction.';if(file.includes('weimaraner'))note='Body shape, pose, coat contrast and contextual structure may have contributed to this false positive.';return `<article class="card" data-cat="${cat}"><a href="${url}" target="_blank"><img src="${url}" alt="${lab}: ${breed}" loading="lazy"></a><div class="card-copy"><span class="tag ${cat}">${lab}</span><h3>${breed}</h3><p class="muted">${note}</p></div></article>`}).join('');document.querySelectorAll('.filter').forEach(b=>b.onclick=()=>{document.querySelectorAll('.filter').forEach(x=>x.classList.remove('active'));b.classList.add('active');document.querySelectorAll('.card').forEach(c=>c.hidden=b.dataset.f!=='all'&&c.dataset.cat!==b.dataset.f)});prev.onclick=()=>{if(i){i--;update()}};next.onclick=()=>{if(i<5){i++;update()}};update()});
